[versions]
assertj = "3.27.3"
awaitility = "4.3.0"
aws = "2.31.36"
edc = "0.12.0"
junit-jupiter = "5.12.2"
keycloak = "26.0.5"
mockito = "5.17.0"
mockserver = "5.15.0"
owlapi = "5.5.1"
postgres = "42.7.5"
rest-assured = "5.5.1"
testcontainers = "1.21.0"
tractusx-edc = "0.9.0"
yasson = "3.0.4"

[libraries]
edc-asset-api = { module = "org.eclipse.edc:asset-api", version.ref = "edc" }
edc-core-spi = { module = "org.eclipse.edc:core-spi", version.ref = "edc" }
edc-boot-lib = { module = "org.eclipse.edc:boot-lib", version.ref = "edc" }
edc-callback-static-endpoint = { module = "org.eclipse.edc:callback-static-endpoint", version.ref = "edc" }
edc-catalog-spi = { module = "org.eclipse.edc:catalog-spi", version.ref = "edc" }
edc-contract-spi = { module = "org.eclipse.edc:contract-spi", version.ref = "edc" }
edc-control-plane-spi = { module = "org.eclipse.edc:control-plane-spi", version.ref = "edc" }
edc-controlplane-base-bom = { module = "org.eclipse.edc:controlplane-base-bom", version.ref = "edc" }
edc-controlplane-feature-sql-bom = { module = "org.eclipse.edc:controlplane-feature-sql-bom", version.ref = "edc" }
edc-data-plane-http-spi = { module = "org.eclipse.edc:data-plane-http-spi", version.ref = "edc" }
edc-data-plane-public-api-v2 = { module = "org.eclipse.edc:data-plane-public-api-v2", version.ref = "edc" }
edc-data-plane-selector-spi = { module = "org.eclipse.edc:data-plane-selector-spi", version.ref = "edc" }
edc-dataplane-base-bom = { module = "org.eclipse.edc:dataplane-base-bom", version.ref = "edc" }
edc-dataplane-feature-sql-bom = { module = "org.eclipse.edc:dataplane-feature-sql-bom", version.ref = "edc" }
edc-edr-store-spi = { module = "org.eclipse.edc:edr-store-spi", version.ref = "edc" }
edc-iam-mock = { module = "org.eclipse.edc:iam-mock", version.ref = "edc" }
edc-json-ld-spi = { module = "org.eclipse.edc:json-ld-spi", version.ref = "edc" }
edc-json-ld-lib = { module = "org.eclipse.edc:json-ld-lib", version.ref = "edc" }
edc-junit = { module = "org.eclipse.edc:junit", version.ref = "edc" }
edc-management-api-test-fixtures = { module = "org.eclipse.edc:management-api-test-fixtures", version.ref = "edc" }
edc-oauth2-daps = { module = "org.eclipse.edc:oauth2-daps", version.ref = "edc" }
edc-oauth2-service = { module = "org.eclipse.edc:oauth2-service", version.ref = "edc" }
edc-participant-spi = { module = "org.eclipse.edc:participant-spi", version.ref = "edc" }
edc-policy-spi = { module = "org.eclipse.edc:policy-spi", version.ref = "edc" }
edc-policy-engine-spi = { module = "org.eclipse.edc:policy-engine-spi", version.ref = "edc" }
edc-transaction-spi = { module = "org.eclipse.edc:transaction-spi", version.ref = "edc" }
edc-transform-spi = { module = "org.eclipse.edc:transform-spi", version.ref = "edc" }
edc-vault-hashicorp = { module = "org.eclipse.edc:vault-hashicorp", version.ref = "edc" }
edc-validator-spi = { module = "org.eclipse.edc:validator-spi", version.ref = "edc" }
edc-validator-lib = { module = "org.eclipse.edc:validator-lib", version.ref = "edc" }
edc-web-spi = { module = "org.eclipse.edc:web-spi", version.ref = "edc" }

edc-aws-data-plane-aws-s3 = { module = "org.eclipse.edc.aws:data-plane-aws-s3", version.ref = "edc" }
edc-aws-validator-data-address-s3 = { module = "org.eclipse.edc.aws:validator-data-address-s3", version.ref = "edc" }

tractusx-edc-core-spi = { module = "org.eclipse.tractusx.edc:core-spi", version.ref = "tractusx-edc" }
tractusx-edc-control-plane-migration = { module = "org.eclipse.tractusx.edc:control-plane-migration", version.ref = "tractusx-edc" }
tractusx-edc-data-plane-migration = { module = "org.eclipse.tractusx.edc:data-plane-migration", version.ref = "tractusx-edc" }
tractusx-edc-postgresql-migration = { module = "org.eclipse.tractusx.edc:postgresql-migration-lib", version.ref = "tractusx-edc" }
tractusx-edc-retirement-evaluation-api = { module = "org.eclipse.tractusx.edc:retirement-evaluation-api", version.ref = "tractusx-edc" }
tractusx-edc-retirement-evaluation-core = { module = "org.eclipse.tractusx.edc:retirement-evaluation-core", version.ref = "tractusx-edc" }
tractusx-edc-retirement-evaluation-store-sql = { module = "org.eclipse.tractusx.edc:retirement-evaluation-store-sql", version.ref = "tractusx-edc" }

assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
aws-iam = { module = "software.amazon.awssdk:iam", version.ref = "aws" }
aws-s3 = { module = "software.amazon.awssdk:s3", version.ref = "aws" }
keycloak-admin-client = { module = "org.keycloak:keycloak-admin-client", version.ref = "keycloak" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockserver-netty = { module = "org.mock-server:mockserver-netty", version.ref = "mockserver" }
owlapi-distribution = { module = "net.sourceforge.owlapi:owlapi-distribution", version.ref = "owlapi" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }
testcontainers-localstack = { module = "org.testcontainers:localstack", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-vault = { module = "org.testcontainers:vault", version.ref = "testcontainers" }

yasson = { module = "org.eclipse:yasson", version.ref = "yasson" }
