[versions]
assertj = "3.27.3"
awaitility = "4.2.2"
edc = "0.11.0"
junit-jupiter = "5.11.4"
mockserver = "5.15.0"
rest-assured = "5.5.1"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
edc-boot-lib = { module = "org.eclipse.edc:boot-lib", version.ref = "edc" }
edc-control-plane-api = { module = "org.eclipse.edc:control-plane-api", version.ref = "edc" }
edc-controlplane-base-bom = { module = "org.eclipse.edc:controlplane-base-bom", version.ref = "edc" }
edc-dataplane-base-bom = { module = "org.eclipse.edc:dataplane-base-bom", version.ref = "edc" }
edc-iam-mock = { module = "org.eclipse.edc:iam-mock", version.ref = "edc" }
edc-junit = { module = "org.eclipse.edc:junit", version.ref = "edc" }
edc-management-api-test-fixtures = { module = "org.eclipse.edc:management-api-test-fixtures", version.ref = "edc" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
mockserver-netty = { module = "org.mock-server:mockserver-netty", version.ref = "mockserver" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }
