name: Build and Publish Maven artifacts and Docker Images

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: set gradle project version if publish from tag
        if: github.ref_type == 'tag'
        run: |
          version=${{ github.ref_name }}
          clean_version=`echo ${version} | cut -c 2-` 
          sed -i 's#^version=.*#version='${clean_version}'#g' gradle.properties

      - name: Build
        run: ./gradlew build
        env:
          USERNAME: ${{ secrets.MDS_GH_USER }}
          TOKEN: ${{ secrets.MDS_PAT }}

      - name: Publish Maven Artifacts
        run: ./gradlew publish
        env:
          USERNAME: ${{ secrets.MDS_GH_USER }}
          TOKEN: ${{ secrets.MDS_PAT }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.MDS_GH_USER }}
          password: ${{ secrets.MDS_PAT }}

      - uses: ./.github/actions/publish-docker-image
        with:
          runtime: connector-vault-postgresql
          image-title: MDS EDC
          image-description: MDS EDC Vault Postgresql connector for production use.

      - uses: ./.github/actions/publish-docker-image
        with:
          runtime: connector-inmemory
          image-title: MDS EDC In Memory
          image-description: MDS EDC In Memory for development purposes.

      - uses: ./.github/actions/publish-docker-image
        with:
          runtime: connector-vault-postgresql-edp
          image-title: MDS EDC EDP Experimental
          image-description: MDS EDC connector with EDP extension for production use.
