name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase_gh_repo
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Build and push inmemory image
        uses: docker/build-push-action@v4
        with:
          context: ./launchers
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ steps.lowercase_gh_repo.outputs.lowercase }}/connector-inmemory:latest
          build-args: |
            RUNTIME=connector-inmemory

      - name: Build and push vault postgresql image
        uses: docker/build-push-action@v4
        with:
          context: ./launchers
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ steps.lowercase_gh_repo.outputs.lowercase }}/connector-vault-postgresql:latest
          build-args: |
            RUNTIME=connector-vault-postgresql
